// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFotbTyHis2DEj2X6Ly07jhER-vvIdLeo',
    appId: '1:928583254340:web:0477c6b6842a730206d711',
    messagingSenderId: '928583254340',
    projectId: 'lightman-34d70',
    authDomain: 'lightman-34d70.firebaseapp.com',
    storageBucket: 'lightman-34d70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YswYgmFvJzUlXQqAL9gvOOCiivOa6gI',
    appId: '1:928583254340:android:1cbad2ab134564e906d711',
    messagingSenderId: '928583254340',
    projectId: 'lightman-34d70',
    storageBucket: 'lightman-34d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9FGUmG_-gZcqxe_HU9JgA1hKVec3PRhM',
    appId: '1:928583254340:ios:53b6ebb6b22bbdd606d711',
    messagingSenderId: '928583254340',
    projectId: 'lightman-34d70',
    storageBucket: 'lightman-34d70.firebasestorage.app',
    iosBundleId: 'com.example.lightman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9FGUmG_-gZcqxe_HU9JgA1hKVec3PRhM',
    appId: '1:928583254340:ios:53b6ebb6b22bbdd606d711',
    messagingSenderId: '928583254340',
    projectId: 'lightman-34d70',
    storageBucket: 'lightman-34d70.firebasestorage.app',
    iosBundleId: 'com.example.lightman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFotbTyHis2DEj2X6Ly07jhER-vvIdLeo',
    appId: '1:928583254340:web:ced54cb14c6d95c306d711',
    messagingSenderId: '928583254340',
    projectId: 'lightman-34d70',
    authDomain: 'lightman-34d70.firebaseapp.com',
    storageBucket: 'lightman-34d70.firebasestorage.app',
  );

}